export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';


const modalTypes = {
    ADD_APPOINTMENT: 'ADD_APPOINTMENT',
    DEL_APPOINTMENT: 'DEL_APPOINTMENT',
    ADD_BOILER: 'ADD_BOILER',
    DEL_BOILER: 'DEL_BOILER',
    ADD_BOILERTYPE: 'ADD_BOILERTYPE',
    DEL_BOILERTYPE: 'DEL_BOILERTYPE',
    ADD_BUILDING: 'ADD_BUILDING',
    DEL_BUILDING: 'DEL_BUILDING',
    ADD_CUSTOMER: 'ADD_CUSTOMER',
    DEL_CUSTOMER: 'DEL_CUSTOMER',
    ADD_TECHNICIAN: 'ADD_TECHNICIAN',
    DEL_TECHNICIAN: 'DEL_TECHNICIAN',
};

export default modalTypes;