//GET DATA
export const GET_BOILER_FETCHING = 'GET_BOILER_FETCHING';
export const GET_BOILER_FULFILLED = 'GET_BOILER_FULFILLED';
export const GET_BOILER_REJECTED = 'GET_BOILER_REJECTED';

//ADD DATA
export const ADD_BOILER_FETCHING = 'ADD_BOILER_FETCHING';
export const ADD_BOILER_FULFILLED = 'ADD_BOILER_FULFILLED';
export const ADD_BOILER_REJECTED = 'ADD_BOILER_REJECTED';

//DELETE DATA
export const DEL_BOILER_FETCHING ='DEL_BOILER_FETCHING';
export const DEL_BOILER_FULFILLED ='DEL_BOILER_FULFILLED';
export const DEL_BOILER_REJECTED ='DEL_BOILER_REJECTED';

//EDIT DATA
export const EDIT_BOILER_FETCHING ='EDIT_BOILER_FETCHING';
export const EDIT_BOILER_FULFILLED ='EDIT_BOILER_FULFILLED';
export const EDIT_BOILER_REJECTED ='EDIT_BOILER_REJECTED';