export const LOGIN_FETCHING = 'LOGIN_FETCHING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const LOGOUT_FETCHING = 'LOGOUT_FETCHING';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';

export const SET_AUTHENTIFICATION ='SET_AUTHENTIFICATION';